name: Strava running graph
on:
  push:
  schedule:
    - cron: "0 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Update graph
        run: python3 graph.py
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_AUTH_CODE: ${{ secrets.STRAVA_AUTH_CODE }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Hourly update
          file_pattern: Strava_run_graph.png
