name: Strava running graph
on:
  push:
  schedule:
    - cron: "0 * * * *"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  RDS_USER: ${{ secrets.RDS_USER }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Start MySQL
        run: sudo systemctl start mysql.service # user:root password:root
      - name: Symbolic link
        run: ln -s star-schema/stardb.py stardb.py
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Update graph
        run: python3 graph.py
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_AUTH_CODE: ${{ secrets.STRAVA_AUTH_CODE }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
